Added Component Content Box
ezsystems/ui-guidelines pull request #9
Opened 2017-08-25 03:08 UTC by inakijv

Most important aspects:
- Added Default Content Box and Default Content Box List.
![screen shot 2017-08-24 at 11 06 12 pm](https://user-images.githubusercontent.com/9256718/29698097-0fc81f0c-8921-11e7-8c47-673c97ed47b2.png)

2017-08-25 03:13 UTC, inakijv commented
Ping @SylvainGuittard

2017-08-25 13:20 UTC, dpobel commented
I don't really see the point in introducing a new component for that. That's visually very close to the table toolbar (if we except the background color). Also given how those toolbars are implemented in Hybrid Platform UI (see [the CSS](https://github.com/ezsystems/hybrid-platform-ui/blob/master/src/bundle/Resources/public/css/modules/list-toolbar.css) and for instance [this template](https://github.com/ezsystems/hybrid-platform-ui/blob/de65dee7aa1f6588bc309c8b48de588688f6fd32/src/bundle/Resources/views/content/tabs/urls.html.twig#L42-L44)) I think this should be a small variation of the list-toolbar (whose name is wrong and should be change as we use it for others things than *list* like here), that way we could get the expected result with the following markup:

```html
<div class="ez-list-toolbar ez-list-toolbar-contentbox">
    <h2 class="ez-list-toolbar-label"></h2>
</div>
```

2017-08-25 13:32 UTC, dpobel commented
(erased my previous comment which was wrong)

Hybrid Platform UI has a component *list toolbar* to implement similar UI for tables (see [CSS](https://github.com/ezsystems/hybrid-platform-ui/blob/master/src/bundle/Resources/public/css/modules/list-toolbar.css) and [example](https://github.com/ezsystems/hybrid-platform-ui/blob/de65dee7aa1f6588bc309c8b48de588688f6fd32/src/bundle/Resources/views/content/tabs/urls.html.twig#L42-L44). I think we should reuse that for this component. So basically the markup (btw didn't you forget to commit/push some HTML file?) could be:

```html
<div class="ez-contentbox">
  <div class="ez-list-toolbar">
    <h2 class="ez-list-toolbar-label">Whatever title</h2>
  </div>
  <div class="ez-contentbox-body">
    <p>Some content</p>
  </div>
</div>
```

2017-08-25 15:03 UTC, inakijv commented
Updated @dpobel. Thank you for pointing html changes out

2017-08-25 15:10 UTC, inakijv commented
Ping @SylvainGuittard

2017-08-28 21:32 UTC, SylvainGuittard requested changes

2017-08-28 21:32 UTC, SylvainGuittard commented on css/components/contentbox.css
> +.ez-contentbox-list  .contentbox-value p {
CS: extra space

2017-08-28 21:38 UTC, SylvainGuittard commented
+1 besides my comment

2017-08-31 14:09 UTC, SylvainGuittard approved these changes

2017-08-31 14:26 UTC, merged